name: Docker Image Security Scan

on:
  push:
    branches: [ "cortex-cli" ]

jobs:
  scan-image:
    runs-on: ubuntu-latest
    environment: Cortex
    env:
      CORTEX_API_KEY: ${{ secrets.CORTEX_API_KEY }}
      CORTEX_API_KEY_ID: ${{ secrets.CORTEX_API_KEY_ID }}
      CORTEX_API_URL: ${{ secrets.CORTEX_API_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pull DVWA Image
        run: docker pull vulnerables/web-dvwa:latest

      - name: Download cortexcli
        run: |
         crtx_resp=$(curl -H "x-xdr-auth-id: ${CORTEX_API_KEY_ID}" -H "Authorization: ${CORTEX_API_KEY}" "${CORTEX_API_URL}/public_api/v1/unified-cli/releases/download-link?os=linux&architecture=amd64")
         crtx_url=$(echo $crtx_resp | jq -r ".signed_url")
         curl -o cortexcli $crtx_url
         chmod +x cortexcli
         ./cortexcli --version

      - name: Scan Image with Cortex
        run: |
         sudo  ./cortexcli --api-base-url "${CORTEX_API_URL}" --api-key-id "${CORTEX_API_KEY_ID}" --api-key "${CORTEX_API_KEY}" --log-level INFO image scan vulnerables/web-dvwa:latest

      - name: Upload Scan Results
        uses: actions/upload-artifact@v4
        with:
          name: security-scan-report
          path: scan-results.json
